### ISSUE TITLE
Link added to patchbay.pub

### ISSUE THREAD

**Issue by anderspitman** [VictorioBerra/patch-me#4]
Hi @VictorioBerra, just wanted to let you know I added a link to patchbay-me to the patchbay.pub homepage. Thanks for the project!

**Comment by VictorioBerra** [comment]
@anderspitman Wow thanks for doing that! If you can think of any cool features you would like to see in the GUI feel free to open an issue and ill do my best to implement.

**Comment by anderspitman** [comment]
For sure. I haven't made much time to play with it yet, but it looks really slick. Projects like this are important, since patchbay is pretty low level. Something I've wanted to do is make a mobile app that helps people manage their patchbay channels, so they can reuse the same ones ie for sending notifications and things.

**Comment by VictorioBerra** [comment]
Re-using the channels is a great idea.

Currently the app is mobile friendly, but does not save state. I could add PWA functionality and then drop in something like [IndexedDB](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API) and then next time a user visits the site their resolved requests would still be there. Couple that by adding a restart button and then maybe adding ability to replace POST requests in the composer and that should cover the 90%.

Ill keep thinking on this and report back when I have some time to plug away at it.

**Comment by VictorioBerra** [comment]
@anderspitman [Big update.](https://patchme.link/) 

- Almost everything you do is now persisted to LocalStorage. 
- You can "clone" a previous request to reuse a channel, you can remove channels.
- if state gets out of whack, you can purge all of it from the left menu ("Reset Local State").
- there is a sync button now so you can sync the current URL and channel to the publisher (click the hamburger menu in the upper-right, or click the hamburger menu in the upper-left and click publisher)

The publisher is something im still finalizing or maybe doing away with entirely. I might just add a "GET/POST" toggle in the UI and then add a payload textbox. Ill just have to re-org the UI a bit to make it more obvious.

I went with LocalStorage because its full-client side still. No server is needed but the only issue there is LocalNotifications do not work too well for mobile devices. For that to work you need a server and some push notification bits from Google. Its not trivial, especially because of the way apps get backgrounded.
